---
id: 201711-patterns-software-engineering
base_name: 201711-patterns-software-engineering
tags:
- rabbit
- patterns
- design patterns
- architectural patterns
presentation_date: 2017-11-23
version: 2017.11.21.1
licenses:
- MIT
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Giovanni Sakti
  email: giosakti@gmail.com
  rubygems_user: giosakti
  slideshare_user:
  speaker_deck_user: giosakti 
